# Generated by Django 3.2.18 on 2023-08-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
